# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 044d07027d458482fba4ee6b74f354c5591dbd258855237f024387a08ebf6ce70fafe0513f4117b5dfc0e1eb833be7fec5288e821ffd389049428a7e6ce236d6

test:
  secret_key_base: 5c85ad6cfd31996377603fb6c623a441e62b580283c2b5f4f0a8e40fded5c8ae065694e0739eb223a5bc3631ddef3657a224add022a6607ede4b877d23a76415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
